### ISSUE TITLE
Add support for streaming

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/PSNeo4j#10]
likely a common parameter, consider defaulting to true

http://neo4j.com/docs/developer-manual/current/http-api/#rest-api-streaming

**Comment by davidwallis3101** [comment]
dont know if this has broken something? 

having run 

```Set-PSNeo4jConfiguration -Credential $Cred -BaseUri 'http://127.0.0.1:7474'

I then get:

![image](https://user-images.githubusercontent.com/13855486/30205095-bac61620-947f-11e7-879d-cd1e867381b1.png)

**Comment by RamblingCookieMonster** [comment]
Yep!  That's a result of me changing the properties in the config file.  Writing a `Initialize-PSNeo4jConfiguration` - until then, you can just set it explicitly via `Set-PSNeo4jConfiguration -Streaming $True` (or `$False`), that should get it up and running again.

Cheers!

**Comment by RamblingCookieMonster** [comment]
Closing this out for now.  If anyone ends up wanting it available on individual commands, feel free to open up a new issue!
