### ISSUE TITLE
Merge relationship

### ISSUE THREAD

**Issue by gpduck** [RamblingCookieMonster/PSNeo4j#19]
Is there a way to merge/update a relationship with New-Neo4jRelationship (like the way Set-Neo4jNode works), or do we need to write Set-Neo4jRelationship?

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Hmm - would have to play around with it.  New-Neo4jRelationship defaults to constructing a `MERGE` [statement](https://github.com/RamblingCookieMonster/PSNeo4j/blob/master/PSNeo4j/Public/New-Neo4jRelationship.ps1#L106).  I don't do something like [this](https://github.com/RamblingCookieMonster/PSNeo4j/blob/master/PSNeo4j/Public/Set-Neo4jNode.ps1#L151) - guessing we might need a set-neo4jrelationship to avoid creating dupes if you want to update a prop, for example

**Comment by RamblingCookieMonster** [comment]
Bah!  And now I need this : )  Will poke around next week

**Comment by gpduck** [comment]
I have a function that I put together, but I didn't dig down to get a good understanding of how these functions work so I'm not sure it's fully functional.  I'll get it uploaded to my fork and shoot a link over so you can have it to start with if you want.

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks @gpduck, borrowed : )
